"""USPS Publication 28 - Secondary Unit Designator Abbreviations."""

UNIT_MAP: dict[str, str] = {
    "APARTMENT": "APT", "APT": "APT",
    "BASEMENT": "BSMT", "BSMT": "BSMT",
    "BUILDING": "BLDG", "BLDG": "BLDG",
    "DEPARTMENT": "DEPT", "DEPT": "DEPT",
    "FLOOR": "FL", "FL": "FL",
    "FRONT": "FRNT", "FRNT": "FRNT",
    "HANGAR": "HNGR", "HNGR": "HNGR",
    "KEY": "KEY",
    "LOBBY": "LBBY", "LBBY": "LBBY",
    "LOT": "LOT",
    "LOWER": "LOWR", "LOWR": "LOWR",
    "OFFICE": "OFC", "OFC": "OFC",
    "PENTHOUSE": "PH", "PH": "PH",
    "PIER": "PIER",
    "REAR": "REAR",
    "ROOM": "RM", "RM": "RM",
    "SIDE": "SIDE",
    "SLIP": "SLIP",
    "SPACE": "SPC", "SPC": "SPC",
    "STOP": "STOP",
    "SUITE": "STE", "STE": "STE",
    "TRAILER": "TRLR", "TRLR": "TRLR",
    "UNIT": "UNIT", "UN": "UNIT",
    "UPPER": "UPPR", "UPPR": "UPPR",
    "#": "#", "NUMBER": "#", "NUM": "#", "NO": "#",
}
