"""DB-backed tests for training_batches CRUD + assignment helpers."""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
import sqlalchemy as sa

if TYPE_CHECKING:
    from sqlalchemy.ext.asyncio import AsyncEngine

from address_validator.db.tables import (
    candidate_batch_assignments,
    model_training_candidates,
    training_batches,
)
from address_validator.services.training_batches import (
    InvalidTransitionError,
    assign_candidates,
    create_batch,
    transition_status,
    unassign_candidates,
)


@pytest.fixture()
async def clean_db(db: AsyncEngine) -> AsyncEngine:
    """Extend `db` fixture by truncating the tables these tests touch."""
    async with db.begin() as conn:
        await conn.execute(
            sa.text(
                "TRUNCATE candidate_batch_assignments, training_batches,"
                " model_training_candidates RESTART IDENTITY CASCADE"
            )
        )
    return db


async def _insert_candidate(engine: AsyncEngine, raw: str) -> str:
    """Insert a candidate row and return its raw_address_hash (generated by DB)."""
    async with engine.begin() as conn:
        await conn.execute(
            sa.text(
                "INSERT INTO model_training_candidates "
                "(raw_address, failure_type, parsed_tokens, status) "
                "VALUES (:raw, 'repeated_label_error', '[[\"1\",\"AddressNumber\"]]'::jsonb, 'new')"
            ),
            {"raw": raw},
        )
        h = (
            await conn.execute(
                sa.select(model_training_candidates.c.raw_address_hash).where(
                    model_training_candidates.c.raw_address == raw
                )
            )
        ).scalar_one()
    return h


async def test_create_batch_starts_planned(clean_db: AsyncEngine) -> None:
    batch_id = await create_batch(clean_db, slug="test-a", description="desc")
    async with clean_db.connect() as conn:
        row = (
            await conn.execute(sa.select(training_batches).where(training_batches.c.id == batch_id))
        ).first()
    assert row.status == "planned"
    assert row.current_step is None


async def test_transition_planned_to_deployed_rejected(clean_db: AsyncEngine) -> None:
    batch_id = await create_batch(clean_db, slug="test-b", description="desc")
    with pytest.raises(InvalidTransitionError):
        await transition_status(clean_db, batch_id=batch_id, target="deployed")


async def test_assign_activates_planned_batch(clean_db: AsyncEngine) -> None:
    batch_id = await create_batch(clean_db, slug="test-c", description="desc")
    h = await _insert_candidate(clean_db, "123 MAIN ST")

    n = await assign_candidates(clean_db, batch_id=batch_id, raw_address_hashes=[h])
    assert n == 1

    async with clean_db.connect() as conn:
        batch = (
            await conn.execute(sa.select(training_batches).where(training_batches.c.id == batch_id))
        ).first()
        cand = (
            await conn.execute(
                sa.select(model_training_candidates.c.status).where(
                    model_training_candidates.c.raw_address_hash == h
                )
            )
        ).first()
    assert batch.status == "active"
    assert batch.activated_at is not None
    assert cand.status == "assigned"


async def test_assign_is_idempotent(clean_db: AsyncEngine) -> None:
    batch_id = await create_batch(clean_db, slug="test-d", description="desc")
    h = await _insert_candidate(clean_db, "456 OAK AVE")
    await assign_candidates(clean_db, batch_id=batch_id, raw_address_hashes=[h])
    n2 = await assign_candidates(clean_db, batch_id=batch_id, raw_address_hashes=[h])
    assert n2 == 0


async def test_unassign_last_batch_reverts_to_new(clean_db: AsyncEngine) -> None:
    batch_id = await create_batch(clean_db, slug="test-e", description="desc")
    h = await _insert_candidate(clean_db, "789 ELM RD")
    await assign_candidates(clean_db, batch_id=batch_id, raw_address_hashes=[h])

    await unassign_candidates(clean_db, batch_id=batch_id, raw_address_hashes=[h])

    async with clean_db.connect() as conn:
        cand = (
            await conn.execute(
                sa.select(model_training_candidates.c.status).where(
                    model_training_candidates.c.raw_address_hash == h
                )
            )
        ).first()
        remaining = (
            await conn.execute(
                sa.select(sa.func.count())
                .select_from(candidate_batch_assignments)
                .where(candidate_batch_assignments.c.raw_address_hash == h)
            )
        ).scalar()
    assert cand.status == "new"
    assert remaining == 0


async def test_unassign_keeps_assigned_when_other_batch_still_holds(
    clean_db: AsyncEngine,
) -> None:
    b1 = await create_batch(clean_db, slug="test-f1", description="desc")
    b2 = await create_batch(clean_db, slug="test-f2", description="desc")
    h = await _insert_candidate(clean_db, "321 PINE ST")
    await assign_candidates(clean_db, batch_id=b1, raw_address_hashes=[h])
    await assign_candidates(clean_db, batch_id=b2, raw_address_hashes=[h])

    await unassign_candidates(clean_db, batch_id=b1, raw_address_hashes=[h])

    async with clean_db.connect() as conn:
        cand = (
            await conn.execute(
                sa.select(model_training_candidates.c.status).where(
                    model_training_candidates.c.raw_address_hash == h
                )
            )
        ).first()
    assert cand.status == "assigned"
